import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdea4",
        "surface-container-lowest": "#ffffff",
        primary: "#785915",
        "on-primary-fixed": "#261900",
        "on-surface": "#1c1c19",
        "secondary-container": "#e2e2e2",
        "tertiary-container": "#d3ae6e",
        surface: "#fcf9f4",
        "on-tertiary-container": "#5b410a",
        "surface-container": "#f0ede9",
        "on-tertiary-fixed": "#271900",
        "on-primary-container": "#5b4100",
        "surface-tint": "#785915",
        tertiary: "#775a22",
        "inverse-surface": "#31302d",
        secondary: "#5e5e5e",
        "surface-container-highest": "#e5e2dd",
        background: "#fcf9f4",
        "secondary-fixed-dim": "#c6c6c6",
        "on-surface-variant": "#4e4639",
        "on-background": "#1c1c19",
        "inverse-primary": "#eac173",
        "surface-container-low": "#f6f3ee",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1b1b1b",
        "surface-variant": "#e5e2dd",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5d4200",
        "tertiary-fixed": "#ffdea8",
        "outline-variant": "#d1c5b5",
        "surface-container-high": "#ebe8e3",
        "tertiary-fixed-dim": "#e7c17f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#eac173",
        "secondary-fixed": "#e2e2e2",
        "inverse-on-surface": "#f3f0eb",
        "on-secondary-container": "#646464",
        "primary-container": "#d5ae62",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#474747",
        outline: "#7f7668",
        "on-tertiary-fixed-variant": "#5c420c",
        "surface-dim": "#dcdad5",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#fcf9f4",
        error: "#ba1a1a",
      },
      fontFamily: {
        headline: ["var(--font-noto-serif)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "2px",
        lg: "2px",
        xl: "4px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
